INSERT INTO SIMULATIONS(ID, NUMBER_OF_ROLLS, NUMBER_OF_DICES, NUMBER_OF_SIDES) VALUES (1, 10, 3, 6);
INSERT INTO SIMULATIONS(ID, NUMBER_OF_ROLLS, NUMBER_OF_DICES, NUMBER_OF_SIDES) VALUES (2, 5, 3, 6);

INSERT INTO RESULTS VALUES (1, 2, 1);
INSERT INTO RESULTS VALUES (2, 2, 1);
INSERT INTO RESULTS VALUES (3, 2, 1);
INSERT INTO RESULTS VALUES (4, 2, 1);
INSERT INTO RESULTS VALUES (5, 2, 1);
INSERT INTO RESULTS VALUES (6, 2, 1);
INSERT INTO RESULTS VALUES (7, 2, 1);
INSERT INTO RESULTS VALUES (8, 2, 1);
INSERT INTO RESULTS VALUES (9, 2, 1);
INSERT INTO RESULTS VALUES (10, 2, 1);
INSERT INTO RESULTS VALUES (11, 2, 2);
INSERT INTO RESULTS VALUES (12, 2, 2);
INSERT INTO RESULTS VALUES (13, 2, 2);
INSERT INTO RESULTS VALUES (14, 2, 2);
INSERT INTO RESULTS VALUES (15, 2, 2);

